apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
  namespace: monitoring
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-08c1b11cc99ddfe95
    fsType: ext4