apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: 352708296901.dkr.ecr.us-west-1.amazonaws.com/jihadpolybot:2.5
        ports:
        - containerPort: 8443
        env:
          - name: TELEGRAM_TOKEN
            value: "6920865650:AAFlBnucpRzJhexXQQSEdYaZ50EFiU60vn4"
          - name: TELEGRAM_APP_URL
            value: "https://polybotjihad.devops-int-college.com/"
          - name: cert_data_base64
            valueFrom:
              secretKeyRef:
                name: bot-certificate
                key: tls.crt
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
          - name: bot-certificate
            mountPath: /etc/ssl/certs
            readOnly: true
      volumes:
        - name: bot-certificate
          secret:
            secretName: bot-certificate

---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
