groups:
- name: nginx-ingress-alerts
  rules:
  - alert: HighRequestRate
    expr: rate(nginx_ingress_controller_requests[1m]) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High request rate detected for Nginx Ingress Controller."
      description: "The rate of incoming requests to the Nginx Ingress Controller is above 100 requests per minute."

  - alert: IngressCertificateExpirationWarning
    expr: (nginx_ingress_controller_ssl_expire_time - time()) < 7*24*3600
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "TLS certificate for Nginx Ingress Controller is expiring soon."
      description: "The TLS certificate used by the Nginx Ingress Controller is expiring in less than 7 days."