apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
      - name: polybot
        image: 352708296901.dkr.ecr.us-west-1.amazonaws.com/jihad-polybot-dev:0.0.13
        ports:
        - containerPort: 8443
        env:
          - name: TELEGRAM_TOKEN
            value: "6920865650:AAFlBnucpRzJhexXQQSEdYaZ50EFiU60vn4"
          - name: TELEGRAM_APP_URL
            value: "https://polybotjihad.devops-int-college.com/"
          - name: S3_BUCKET_NAME
            value: "jihadar"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
             secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
             secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
