apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-5-190.us-west-1.compute.internal
      containers:
      - name: yolo5
        image: 352708296901.dkr.ecr.us-west-1.amazonaws.com/jihad-yolo5-prod:0.0.43
        ports:
        - containerPort: 8080
        env:
          - name: BUCKET_NAME
            value: "jihadar"
          - name: SQS_QUEUE_NAME
            value: "jihad"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            cpu: "100m"
            memory: "150Mi"
          limits:
            cpu: "1000m"
            memory: "3Gi"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
 namespace: prod
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: yolo5-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
